// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DAL
{
    public partial interface IAppDbContextProcedures
    {
        Task<int> usp_addemployeeAsync(string Name, string Address, int? DepartmentId, OutputParameter<int?> Status, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_deleteemployeeAsync(int? Id, OutputParameter<int?> Status, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getemployeeResult>> usp_getemployeeAsync(int? EmployeeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getemployeesResult>> usp_getemployeesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_updateemployeeAsync(int? Id, string Name, string Address, int? DepartmentId, OutputParameter<int?> Status, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
